import Head from "next/head";
import Main from "../components/Home/Home";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Dogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.jpg" />
      </Head>
      <Main />
    </div>
  );
}
